In [2]:
import pandas

In [3]:
pandas.__version__

'1.2.4'

In [4]:
import numpy as np

In [5]:
mylist = [1,2,3,7]

In [6]:
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3, 7])

In [8]:
mylist

[1, 2, 3, 7]

In [9]:
myarr = np.array(mylist)

In [10]:
type(myarr)

numpy.ndarray

In [11]:
len(myarr)

4

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,17,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3,4)

array([[0.09781392, 0.85984785, 0.46924468, 0.16494324],
       [0.87389571, 0.25822255, 0.86166986, 0.77083906],
       [0.72881733, 0.29248233, 0.58831362, 0.4099161 ]])

In [22]:
np.random.randn(4)

array([-0.66432067, -1.28372832,  0.19946607,  0.1781376 ])

In [23]:
np.random.randint(52,5489484,(4,5))

array([[ 234577, 3799418, 3937839, 4018045, 4026130],
       [2831604,  682586, 4225411, 4267908, 2535389],
       [3909731,  306484, 2044322,   52592, 4798258],
       [3989899, 5243877, 1439273,  202184, 3127005]])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
arr = np.arange(0,25)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
randarr = np.random.randint(0,101,8)

In [28]:
randarr = randarr.reshape (2,4)

In [29]:
randarr.max()

99

In [30]:
randarr.argmax()

5

In [31]:
randarr.argmin()

7

In [32]:
randarr.dtype

dtype('int32')

In [33]:
randarr.shape

(2, 4)

In [34]:
#import psycopg2

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[8]

8

In [38]:
arr[1:15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[0:5] =100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice_of_arr = arr[:5]

In [46]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [47]:
slice_of_arr[:] = 99

In [48]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr_copy[:] = 873

In [52]:
arr_copy

array([873, 873, 873, 873, 873, 873, 873, 873, 873, 873, 873])

In [53]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d.shape

(3, 3)

In [56]:
arr_2d[0]

array([ 5, 10, 15])

In [57]:
arr_2d[2]

array([35, 40, 45])

In [58]:
arr_2d[2][0]

35

In [59]:
arr_2d[1,1]

25

In [60]:
arr_2d[0,2]

15

In [61]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
bool_arr = arr>4

In [68]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
import numpy as np


In [71]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

# total_rolls_over_two = # This should be a single integer
counter =  0
total_rolls_over_two = 0
for x in range(0,len(dice_rolls)):
    
    if dice_rolls[x] > 2:
        
        total_rolls_over_two +=1
    else:
        pass
    counter +=1

print(adder)

NameError: name 'adder' is not defined

In [72]:
len(dice_rolls[dice_rolls>2])

19

In [73]:
for x in range(0,10):
    print (x)

0
1
2
3
4
5
6
7
8
9


In [74]:
import numpy as np
import pandas as pd

In [75]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [76]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [77]:
myindex = ['CA','NY','AZ','TX']

In [78]:
mycolumns = ['Jan','Feb','Mar']

In [79]:
df= pd.DataFrame(data=mydata,index=myindex,columns =mycolumns)

In [80]:
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [82]:
#where is my python code located

In [83]:
pwd

'C:\\Users\\User\\Desktop\\EDUCATION\\Python Learning\\Python Data Science and Machine Learning\\Setup and Environments\\03-Pandas'

In [84]:
ls

 Volume in drive C has no label.
 Volume Serial Number is DE03-C73A

 Directory of C:\Users\User\Desktop\EDUCATION\Python Learning\Python Data Science and Machine Learning\Setup and Environments\03-Pandas

14/06/2021  11:09 AM    <DIR>          .
14/06/2021  11:09 AM    <DIR>          ..
11/06/2021  11:13 AM    <DIR>          .ipynb_checkpoints
13/07/2020  02:07 AM    <DIR>          __pycache__
11/06/2021  12:55 AM           565,514 00-Series.ipynb
09/09/2020  12:59 AM           208,957 01-DataFrames.ipynb
09/09/2020  12:59 AM           194,591 02-Conditional-Filtering.ipynb
13/08/2020  07:49 AM           196,385 03-Useful-Methods.ipynb
02/07/2020  05:32 AM            64,227 04-Missing-Data.ipynb
05/07/2020  03:28 AM           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
05/07/2020  05:19 AM            62,966 06-Combining-DataFrames.ipynb
26/09/2020  01:04 AM            32,972 07-Text-Methods.ipynb
09/09/2020  12:59 AM            93,392 08-Time-Methods.ipynb
26/09/2020  06:48 AM 

In [85]:
df = pd.read_csv('tips.csv')

In [86]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [88]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [89]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [90]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [91]:
df['total_bill'].std()

8.902411954856856

In [92]:
#mycols = ['total_bill','tip']
#df[mycols]

df[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [93]:
df['tip_percentage'] = 100*df['tip'] / df['total_bill']


In [94]:
df['tip_percentage']

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...    
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Name: tip_percentage, Length: 244, dtype: float64

In [95]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID',
       'tip_percentage'],
      dtype='object')

In [96]:
np.round(df['tip_percentage'],2)

0       5.94
1      16.05
2      16.66
3      13.98
4      14.68
       ...  
239    20.39
240     7.36
241     8.82
242     9.82
243    15.97
Name: tip_percentage, Length: 244, dtype: float64

In [97]:
df['tip_percentage'] = np.round(df['tip_percentage'],2)

In [98]:
df['tip_percentage'] 

0       5.94
1      16.05
2      16.66
3      13.98
4      14.68
       ...  
239    20.39
240     7.36
241     8.82
242     9.82
243    15.97
Name: tip_percentage, Length: 244, dtype: float64

In [99]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  tip_percentage  
0    Christy Cunningham  3560325168603410    Sun2959            5.94  
1        Douglas Tucker  4478071379779230    Sun4608           16.05  
2        Travis Walters  6011812112971322    Sun4458           16.66  
3      Nathaniel Harris  4676137647685994    Sun5260           13.98  
4          Tonya Carter  4832732618637221    Sun2251           14.68  
..                  ...               ...        ...             ...  
239       Michael Avila  5296068606052842    Sat2657           20.39  
240      Monica Sanders  3506806155565404    Sat1766            7.36  
241          Keith Wong  6011891618747196    Sat3880            8.82  
242        Dennis Dixon     4375220550950      Sat17            9.82  
243     Michelle Hardin  3511451626698139    Thur672           15.97  

[244 rows x 12 columns]

In [100]:
df.drop('tip_percentage',axis =1)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [101]:
df.shape

(244, 12)

In [102]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [103]:
df.tail(3)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  tip_percentage  
241       Keith Wong  6011891618747196    Sat3880            8.82  
242     Dennis Dixon     4375220550950      Sat17            9.82  
243  Michelle Hardin  3511451626698139    Thur672           15.97

In [104]:
df = df.set_index("Payment ID")

In [105]:
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  \
Payment ID                                                           
Sun2959                 8.49  Christy Cunningham  3560325168603410   
Sun4608                 3.45      Douglas Tucker  4478071379779230   
Sun4458                 7.00      Travis Walters  6011812112971322   
Sun5260                11.84    Nathaniel Harris  4676137647685994   
Sun2251                 6.15        Tonya Carter  4832732618637221   
...                      ...                 ...               ...   
Sat2657                 9.68       Michael Avila  5296068606052842   
Sat1766                13.59      Monica Sanders  3506806155565404   
Sat3880                11.34          Keith Wong  6011891618747196   
Sat17                   8.91        Dennis Dixon     4375220550950   
Thur672                 9.39     Michelle Hardin  3511451626698139   

            tip_percentage  
Payment ID                  
Sun2959               5.94  
Sun4608              16.05  
Sun4458              16.66  
Sun5260              13.98  
Sun2251              14.68  
...                    ...  
Sat2657              20.39  
Sat1766               7.36  
Sat3880               8.82  
Sat17                 9.82  
Thur672              15.97  

[244 rows x 11 columns]

In [106]:
df=df.reset_index()

In [107]:
#df

In [108]:
df.head(3)

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   

   price_per_person          Payer Name         CC Number  tip_percentage  
0              8.49  Christy Cunningham  3560325168603410            5.94  
1              3.45      Douglas Tucker  4478071379779230           16.05  
2              7.00      Travis Walters  6011812112971322           16.66

In [112]:
df.iloc[0:4]

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   

   price_per_person          Payer Name         CC Number  tip_percentage  
0              8.49  Christy Cunningham  3560325168603410            5.94  
1              3.45      Douglas Tucker  4478071379779230           16.05  
2              7.00      Travis Walters  6011812112971322           16.66  
3             11.84    Nathaniel Harris  4676137647685994           13.98

In [110]:
df.loc['Sun2959':'Sun5260']

Empty DataFrame
Columns: [Payment ID, total_bill, tip, sex, smoker, day, time, size, price_per_person, Payer Name, CC Number, tip_percentage]
Index: []

In [111]:
df.drop('Sun2959', axis=0)

KeyError: "['Sun2959'] not found in axis"

In [113]:
one_row = df.iloc[0]

In [114]:
one_row

Payment ID                     Sun2959
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
tip_percentage                    5.94
Name: 0, dtype: object

In [115]:
df.append(one_row)

Payment ID  total_bill   tip     sex smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2   
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3   
2      Sun4458       21.01  3.50    Male     No   Sun  Dinner     3   
3      Sun5260       23.68  3.31    Male     No   Sun  Dinner     2   
4      Sun2251       24.59  3.61  Female     No   Sun  Dinner     4   
..         ...         ...   ...     ...    ...   ...     ...   ...   
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2   
241    Sat3880       22.67  2.00    Male    Yes   Sat  Dinner     2   
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2   
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2   
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2   

     price_per_person          Payer Name         CC Number  tip_percentage  
0                8.49  Christy Cunningham  3560325168603410            5.94  
1                3.45      Douglas Tucker  4478071379779230           16.05  
2                7.00      Travis Walters  6011812112971322           16.66  
3               11.84    Nathaniel Harris  4676137647685994           13.98  
4                6.15        Tonya Carter  4832732618637221           14.68  
..                ...                 ...               ...             ...  
240             13.59      Monica Sanders  3506806155565404            7.36  
241             11.34          Keith Wong  6011891618747196            8.82  
242              8.91        Dennis Dixon     4375220550950            9.82  
243              9.39     Michelle Hardin  3511451626698139           15.97  
0                8.49  Christy Cunningham  3560325168603410            5.94  

[245 rows x 12 columns]

In [116]:
df = pd.read_csv('tips.csv')

In [117]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [118]:
bool_series = df['total_bill'] >40

In [119]:
df[bool_series]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [120]:
df[df['total_bill'] >40]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [121]:
df[df['sex'] == 'Male']

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[157 rows x 11 columns]

In [122]:
#multiple conditions - AND or OR; both true or one of is true

In [123]:
df[df['total_bill'] >40]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [124]:
df['total_bill'] >30

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [125]:
df[(df['total_bill'] >40 ) & (df['sex'] == 'Male')]

total_bill    tip   sex smoker   day    time  size  price_per_person  \
59        48.27   6.73  Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73  Male    Yes   Fri  Dinner     4             10.04   
142       41.19   5.00  Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00  Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00  Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50  Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00  Male    Yes   Sun  Dinner     2             20.27   
212       48.33   9.00  Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
212  Alex Williamson      676218815212    Sat4590

In [126]:
df[(df['total_bill'] >40 ) | (df['sex'] == 'Male')] # | ,eans or

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[159 rows x 11 columns]

In [127]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [128]:
df[(df['day'] =='Sun' ) | (df['day'] == 'Sat') ]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

In [129]:
# faster method

options = ['Sat','Sun']

In [131]:
df['day'].isin(options)

0       True
1       True
2       True
3       True
4       True
       ...  
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool

In [132]:
df[df['day'].isin(options)]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

In [133]:
df = pd.read_csv('tips.csv')

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [144]:
str(123456789)[-4:-2]

'67'

In [145]:
def last_four(num):
    return str(num)[-4:]

In [146]:
last_four(123456789)

'6789'

In [149]:
df['last_four'] = df['CC Number'].apply(last_four)

In [151]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID last_four  
0  Christy Cunningham  3560325168603410    Sun2959      3410  
1      Douglas Tucker  4478071379779230    Sun4608      9230  
2      Travis Walters  6011812112971322    Sun4458      1322  
3    Nathaniel Harris  4676137647685994    Sun5260      5994  
4        Tonya Carter  4832732618637221    Sun2251      7221

In [155]:
#df['total_bill']

In [157]:
df['total_bill'].mean()

19.78594262295082

In [159]:
def yelp(price):
    if price < 10:
        return '$'
    elif price >= 10 and price < 30:
        return '$$'
    else:
        return '$$$'
    

In [160]:
df['yelp'] = df['total_bill'].apply(yelp)

In [163]:
df[df['yelp'] == '$$$'].head(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
11       35.26  5.00  Female     No  Sun  Dinner     4              8.82   
23       39.42  7.58    Male     No  Sat  Dinner     4              9.86   
39       31.27  5.00    Male     No  Sat  Dinner     3             10.42   
44       30.40  5.60    Male     No  Sun  Dinner     4              7.60   
47       32.40  6.00    Male     No  Sun  Dinner     4              8.10   

           Payer Name         CC Number Payment ID last_four yelp  
11       Diane Macias  4577817359320969    Sun6686      0969  $$$  
23     Lance Peterson  3542584061609808     Sat239      9808  $$$  
39  Mr. Brandon Berry  6011525851069856    Sat6373      9856  $$$  
44        Todd Cooper      503846761263    Sun2274      1263  $$$  
47       James Barnes  3552002592874186    Sun9677      4186  $$$

In [164]:
def simple(num):
    return num**2

In [165]:
simple(4)

16

In [166]:
lambda num: num**2

<function __main__.<lambda>(num)>

In [171]:
df['total_bill'].apply(lambda num: num**2)

0      288.6601
1      106.9156
2      441.4201
3      560.7424
4      604.6681
         ...   
239    842.7409
240    738.7524
241    513.9289
242    317.5524
243    352.6884
Name: total_bill, Length: 244, dtype: float64

In [172]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID last_four yelp  
0  Christy Cunningham  3560325168603410    Sun2959      3410   $$  
1      Douglas Tucker  4478071379779230    Sun4608      9230   $$  
2      Travis Walters  6011812112971322    Sun4458      1322   $$  
3    Nathaniel Harris  4676137647685994    Sun5260      5994   $$  
4        Tonya Carter  4832732618637221    Sun2251      7221   $$

In [173]:
def quality(total_bill,tip):
    if tip/total_bill > 0.25:
        return 'Generous'
    else:
        return "Other"

In [175]:
quality(16,13)

'Generous'

In [177]:
df[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [182]:
df['Quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)

In [183]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID last_four yelp Quality  
0  Christy Cunningham  3560325168603410    Sun2959      3410   $$   Other  
1      Douglas Tucker  4478071379779230    Sun4608      9230   $$   Other  
2      Travis Walters  6011812112971322    Sun4458      1322   $$   Other  
3    Nathaniel Harris  4676137647685994    Sun5260      5994   $$   Other  
4        Tonya Carter  4832732618637221    Sun2251      7221   $$   Other

In [186]:
df['Quality'] = np.vectorize(quality)(df['total_bill'],df['tip'])

In [187]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID last_four yelp Quality  
0  Christy Cunningham  3560325168603410    Sun2959      3410   $$   Other  
1      Douglas Tucker  4478071379779230    Sun4608      9230   $$   Other  
2      Travis Walters  6011812112971322    Sun4458      1322   $$   Other  
3    Nathaniel Harris  4676137647685994    Sun5260      5994   $$   Other  
4        Tonya Carter  4832732618637221    Sun2251      7221   $$   Other

In [189]:
import timeit

In [190]:
# code snippet to be executed only once 
setup = '''
import numpy as np
import pandas as pd
df = pd.read_csv('tips.csv')
def quality(total_bill,tip):
    if tip/total_bill  > 0.25:
        return "Generous"
    else:
        return "Other"
'''
  



In [191]:
# code snippet whose execution time is to be measured 
stmt_one = ''' 
df['Tip Quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)
'''

stmt_two = '''
df['Tip Quality'] = np.vectorize(quality)(df['total_bill'], df['tip'])
'''

In [192]:
timeit.timeit(setup = setup,stmt=stmt_one,number = 1000)

7.742906200001016

In [193]:
timeit.timeit(setup = setup,stmt=stmt_two,number = 1000)

0.574890600022627