In [4]:
import pandas

In [5]:
pandas.__version__

'1.2.4'

In [6]:
import numpy as np

In [7]:
mylist = [1,2,3]

In [8]:
type(mylist)

list

In [9]:
np.array(mylist)

array([1, 2, 3])

In [10]:
mylist

[1, 2, 3]

In [37]:
myarr = np.array(mylist)

In [38]:
type(myarr)

numpy.ndarray

In [57]:
myarr

array([1, 2, 3])

In [40]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [41]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(0,17,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [48]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.random.rand(3,4)

array([[0.02058449, 0.96990985, 0.83244264, 0.21233911],
       [0.18182497, 0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386]])

In [50]:
np.random.randn(4)

array([-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ])

In [51]:
np.random.randint(52,5489484,(4,5))

array([[1954406, 2416234, 3474727, 2653043, 2428440],
       [ 528230, 2663098, 2586696, 2570458, 3416716],
       [3385711, 3385409, 2795565, 1465741,   68200],
       [1825717, 2745735, 3397775, 3003810, 4056570]])

In [52]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [53]:
arr = np.arange(0,25)

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
randarr = np.random.randint(0,101,8)

In [30]:
randarr = randarr.reshape (2,4)

In [55]:
randarr.max()

99

In [56]:
randarr.argmax()

5

In [33]:
randarr.argmin()

7

In [34]:
randarr.dtype

dtype('int32')

In [36]:
randarr.shape

(2, 4)

In [3]:
#import psycopg2

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[8]

8

In [64]:
arr[1:15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[0:5] =100

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
arr = np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
slice_of_arr = arr[:5]

In [72]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [73]:
slice_of_arr[:] = 99

In [74]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [75]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [76]:
arr_copy = arr.copy()

In [77]:
arr_copy[:] = 873

In [78]:
arr_copy

array([873, 873, 873, 873, 873, 873, 873, 873, 873, 873, 873])

In [81]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [82]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
arr_2d.shape

(3, 3)

In [84]:
arr_2d[0]

array([ 5, 10, 15])

In [85]:
arr_2d[2]

array([35, 40, 45])

In [86]:
arr_2d[2][0]

35

In [87]:
arr_2d[1,1]

25

In [88]:
arr_2d[0,2]

15

In [89]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [95]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [96]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
bool_arr = arr>4

In [101]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])