In [1]:
import pandas

In [3]:
pandas.__version__

'1.2.4'

In [5]:
import numpy as np

In [6]:
mylist = [1,2,3]

In [9]:
type(mylist)

list

In [10]:
np.array(mylist)

array([1, 2, 3])

In [11]:
mylist

[1, 2, 3]

In [12]:
myarr = np.array(mylist)

In [13]:
type(myarr)

numpy.ndarray

In [14]:
myarr

array([1, 2, 3])

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(0,17,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [38]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.random.rand(3,4)

array([[0.34996462, 0.60332664, 0.57783856, 0.24567537],
       [0.54827708, 0.8927811 , 0.91613185, 0.23291881],
       [0.34804239, 0.7175899 , 0.89857815, 0.83036713]])

In [50]:
np.random.randn(4)

array([0.32430084, 1.33260491, 1.1801557 , 0.55903078])

In [70]:
np.random.randint(52,5489484,(4,5))

array([[2234541, 1570058, 1136126, 4044939, 1239963],
       [4472523, 2138294, 4523721, 4981557, 1766943],
       [4521425, 3344821,  791795,  103407, 1262804],
       [1396077, 5183792, 1307423,  917092, 2253934]])

In [68]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [71]:
arr = np.arange(0,25)

In [79]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
randarr = np.random.randint(0,101,8)

In [104]:
randarr = randarr.reshape (2,4)

In [92]:
randarr.max()

79

In [97]:
randarr.argmax()

3

In [98]:
randarr.argmin()

2

In [100]:
randarr.dtype

dtype('int32')

In [105]:
randarr.shape

(2, 4)