In [1]:
import pandas

In [3]:
pandas.__version__

'1.2.4'

In [5]:
import numpy as np

In [6]:
mylist = [1,2,3]

In [9]:
type(mylist)

list

In [10]:
np.array(mylist)

array([1, 2, 3])

In [11]:
mylist

[1, 2, 3]

In [12]:
myarr = np.array(mylist)

In [13]:
type(myarr)

numpy.ndarray

In [14]:
myarr

array([1, 2, 3])

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(0,17,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [38]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])