In [1]:
import numpy as np

In [2]:
lst = [1,2,3]

In [4]:
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [8]:
matr = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
matr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
type(matr)

list

In [11]:
tt = np.array(matr)

In [12]:
type(tt)

numpy.ndarray

In [13]:
tt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(3,6,17)

array([3.    , 3.1875, 3.375 , 3.5625, 3.75  , 3.9375, 4.125 , 4.3125,
       4.5   , 4.6875, 4.875 , 5.0625, 5.25  , 5.4375, 5.625 , 5.8125,
       6.    ])

In [22]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(1)

array([0.13056044])

In [26]:
np.random.rand(5,3)

array([[0.90184648, 0.82001503, 0.5910253 ],
       [0.6359761 , 0.9213012 , 0.98828536],
       [0.65246704, 0.4902836 , 0.84173565],
       [0.38016505, 0.0178959 , 0.22999061],
       [0.88871322, 0.26439279, 0.39895375]])

In [27]:
np.random.randn(10)

array([-0.68977236, -1.29877889,  1.9688787 ,  0.599388  , -0.47672651,
       -0.31098228,  1.06223765, -0.82965169,  0.74553339, -0.03426998])

In [28]:
np.random.randn(2,3)

array([[ 1.50858109,  0.73335355,  0.1106033 ],
       [-0.63460936, -0.28559103,  1.72368523]])

In [31]:
np.random.randint(1,50,13)

array([16, 47, 17, 47, 39, 38, 22, 28, 44, 22, 47, 46, 44])

In [32]:
np.random.randint(1,50,(4,3))

array([[47, 42, 10],
       [ 5, 46, 37],
       [15, 24, 40],
       [ 4, 30,  9]])

In [34]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [35]:
arr =np.arange(0,25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.max()

24

In [42]:
arr.min()

0

In [43]:
arr.argmax()

24

In [44]:
arr.argmin()

0

In [46]:
arr = arr.reshape(5,5)

In [47]:
arr.shape

(5, 5)

In [48]:
arr = np.arange(0,11)

In [49]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[4:6] = 99

In [52]:
arr

array([ 0,  1,  2,  3, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr_copy = arr.copy()

In [54]:
arr_copy

array([ 0,  1,  2,  3, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy[:] = 100

In [56]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [57]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d.shape

(3, 3)

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[2]

array([35, 40, 45])

In [62]:
arr_2d[1][1]

25

In [63]:
arr_2d[1,1]

25

In [64]:
arr_2d[0,2]

15

In [65]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [66]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [83]:
arr = np.arange(0,10)

In [71]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
bool_arr = arr>4

In [73]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
arr +5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
arr -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [79]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
   arr/arr

<ipython-input-84-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [85]:
1/arr

<ipython-input-85-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [87]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [88]:
np.log(arr)

<ipython-input-88-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [89]:
arr.mean()

4.5

In [90]:
arr.std()

2.8722813232690143

In [93]:
arr2 = np.arange(0,25)

In [95]:
arr2 = arr2.reshape(5,5)

In [96]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
arr2.sum()

300

In [99]:
arr2.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# PANDAS

In [101]:
import pandas as pd

In [103]:
#help(pd.Series)

In [105]:
myindex =['usa','canada','mexico']

In [107]:
mydata = [1776,1867,1821]

In [111]:
myser = pd.Series(data=mydata,index=myindex)

In [112]:
myser

usa       1776
canada    1867
mexico    1821
dtype: int64

In [113]:
myser[0]

1776

In [114]:
myser['usa']

1776

In [115]:
ages = {'sam':5,'frank':10,'spike':7}

In [116]:
pd.Series(ages)

sam       5
frank    10
spike     7
dtype: int64

In [117]:
# Imaginary Sales Data for 1st and 2nd Quarters for Global Company
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [118]:
# Convert into Pandas Series
sales_Q1 = pd.Series(q1)
sales_Q2 = pd.Series(q2)

In [119]:
sales_Q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [122]:
sales_Q1['Japan']

80

In [123]:
sales_Q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [124]:
[1,2]*2

[1, 2, 1, 2]

In [125]:
np.array([1,2])*2

array([2, 4])

In [126]:
sales_Q1/100

Japan    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64

In [127]:
sales_Q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [128]:
sales_Q1+sales_Q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [130]:
sales_Q1.add(sales_Q2,fill_value = 0)

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [131]:
sales_Q1.dtype

dtype('int64')

In [132]:
#DATAFRAMES

In [138]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [139]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [140]:
myindex = ['ca','ny','az','tx']

In [141]:
mycolumns = ['jan','feb','mar']

In [146]:
df = pd.DataFrame(mydata,myindex,mycolumns)

In [147]:
df

jan  feb  mar
ca   95   11   81
ny   70   63   87
az   75    9   77
tx   40    4   63

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, ca to tx
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   jan     4 non-null      int32
 1   feb     4 non-null      int32
 2   mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [153]:
pwd # import commeand only for jupyter

'C:\\Users\\User\\Desktop\\EDUCATION\\Python Learning\\Python Data Science and Machine Learning\\Setup and Environments\\02-Numpy'

In [154]:
import os

In [155]:
os.getcwd()

'C:\\Users\\User\\Desktop\\EDUCATION\\Python Learning\\Python Data Science and Machine Learning\\Setup and Environments\\02-Numpy'

In [156]:
ls

 Volume in drive C has no label.
 Volume Serial Number is DE03-C73A

 Directory of C:\Users\User\Desktop\EDUCATION\Python Learning\Python Data Science and Machine Learning\Setup and Environments\02-Numpy

20/03/2022  06:04 PM    <DIR>          .
20/03/2022  06:04 PM    <DIR>          ..
20/03/2022  04:59 PM    <DIR>          .ipynb_checkpoints
30/06/2020  01:38 PM            25,370 00-NumPy-Arrays.ipynb
15/04/2019  11:56 PM            13,183 01-NumPy-Indexing-and-Selection.ipynb
23/01/2020  12:54 AM            11,648 02-NumPy-Operations.ipynb
20/03/2022  05:38 PM            31,608 03-NumPy-Exercises.ipynb
15/04/2019  11:56 PM            18,561 04-NumPy-Exercises-Solutions.ipynb
15/04/2019  11:56 PM            21,381 axis_logic.png
20/03/2022  06:04 PM            37,415 dsml.ipynb
15/04/2019  11:56 PM            77,025 numpy_indexing.png
               8 File(s)        236,191 bytes
               3 Dir(s)  23,390,797,824 bytes free


In [157]:
df = pd.read_csv('C:\Users\User\Desktop\EDUCATION\Python Learning\Python Data Science and Machine Learning\Setup and Environments\03-Pandas\tips.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-157-b67d688dfab8>, line 1)